scryrall-admin/Models/Carta.cs
using scryrall_admin.NovaPasta1;
using System;
using System.ComponentModel.DataAnnotations;

namespace scryrall_admin.Models
{
	public class Carta
	{
		public int Id { get; set; }
        public string Tipo { get; set; }
        public string Descricao { get; set; }

		[Required]
		[DataType(DataType.ImageUrl)]
		[Display(Name = "Url Foto")]
        public string FotoUrl { get; set; }

        public virtual Link Link { get; set; }
		public virtual Ilustrador Ilustrador { get; set; }
		public virtual Colecao Colecao { get; set; }
		public virtual ICollection<Idioma> Idiomas { get; set; }
		public virtual ICollection<RegrasEspeciais> RegrasEspeciais { get; set; }
		public virtual ICollection<ToolBox> ToolBoxes { get; set; }



        public Carta()
		{
		}
        public Carta(EditDto editDto)
        {
			Tipo = editDto.Tipo;
			Descricao = editDto.Descricao;
			Link.Url = editDto.Url;

        }
    }
}

scryrall-admin/Models/Colecao.cs
using System;
namespace scryrall_admin.Models
{
	public class Colecao
	{
		public int Id { get; set; }
		public string Nome { get; set; }
        public DateTime Ano { get; set; }
        public string LogoUrl { get; set; }

		public virtual Carta Carta { get; set; }



        public Colecao()
		{
		}
	}
}

scryrall-admin/Models/ErrorViewModel.cs
namespace scryrall_admin.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

scryrall-admin/Models/Idioma.cs
using System;
namespace scryrall_admin.Models
{
	public class Idioma
	{
		public string Id { get; set; }
		public string Name { get; set; }
	}
}

scryrall-admin/Models/Ilustrador.cs
using System;
namespace scryrall_admin.Models
{
	public class Ilustrador
	{
		public int Id { get; set; }
        public string Nome { get; set; }

		public virtual Carta Carta { get; set; }



        public Ilustrador()
		{
		}
	}
}

scryrall-admin/Models/Link.cs
using System;
namespace scryrall_admin.Models
{
	public class Link
	{
		public int Id;
		public string Url;

		public virtual Carta Carta { get; set; }


        public Link()
		{
		}
	}
}

scryrall-admin/Models/RegrasEspeciais.cs
using System;
namespace scryrall_admin.Models
{
	public class RegrasEspeciais
	{
		public int Id { get; set; }
        public string Descricao { get; set; }
        public DateTime Data { get; set; }


        public virtual Carta Carta { get; set; }

        public RegrasEspeciais()
		{
		}
	}
}

scryrall-admin/Models/ToolBox.cs
using System;
namespace scryrall_admin.Models
{
	public class ToolBox
	{
		public int Id { get; set; }
		public string nome { get; set; }


		public virtual Carta Carta { get; set; }

        public ToolBox()
		{
		}
	}
}

scryrall-admin/Controllers/CartasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using scryrall_admin.Models;
using scryrall_admin.Persistence;

namespace scryrall_admin.Controllers
{
    public class CartasController : Controller
    {
        private readonly ScryFallDbContext _context;

        public CartasController(ScryFallDbContext context)
        {
            _context = context;
        }

        // GET: Cartas
        public async Task<IActionResult> Index()
        {
              return _context.Cartas != null ? 
                          View(await _context.Cartas.ToListAsync()) :
                          Problem("Entity set 'ScryFallDbContext.Cartas'  is null.");
        }

        // GET: Cartas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Cartas == null)
            {
                return NotFound();
            }
            var carta = await _context.Cartas
                .Include(c => c.Colecao)
                .Include(c => c.Ilustrador)
                .Include(c => c.Link)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carta == null)
            {
                return NotFound();
            }

            return View(carta);
        }

        // GET: Cartas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cartas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Tipo,Descricao,FotoUrl")] Carta carta)
        {
            try
            {
  
                 
                _context.Add(carta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(carta);
        }

        // GET: Cartas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Cartas == null)
            {
                return NotFound();
            }
            var carta = await _context.Cartas
                .Include(c => c.Colecao)
                .Include(c => c.Ilustrador)
                .Include(c => c.Link)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carta == null)
            {
                return NotFound();
            }
            return View(carta);
        }

        // POST: Cartas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Carta carta)
        {
            if (id != carta.Id)
            {
                return NotFound();
            }


            try
            {
                _context.Update(carta);
             

                await _context.SaveChangesAsync();


            } catch (DataException )
            {

            }
            return RedirectToAction(nameof(Index));




        }

        // GET: Cartas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Cartas == null)
            {
                return NotFound();
            }

            var carta = await _context.Cartas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (carta == null)
            {
                return NotFound();
            }

            return View(carta);
        }

        // POST: Cartas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Cartas == null)
            {
                return Problem("Entity set 'ScryFallDbContext.Cartas'  is null.");
            }
            var carta = await _context.Cartas.FindAsync(id);
            if (carta != null)
            {
                _context.Cartas.Remove(carta);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CartaExists(int id)
        {
          return (_context.Cartas?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

scryrall-admin/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using scryrall_admin.Models;

namespace scryrall_admin.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Cartas()
    {
       return RedirectToAction("Index");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

scryrall-admin/Views/Cartas/Create.cshtml
@model scryrall_admin.Models.Carta

@{
    ViewData["Title"] = "Create";
}

<h1>Criar Carta</h1>

<hr />

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Tipo" class="control-label">Tipo</label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Descricao" class="control-label">Descrição</label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="FotoUrl" class="control-label">URL da Imagem</label>
                <input asp-for="FotoUrl" class="form-control" />
                <span asp-validation-for="FotoUrl" class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Criar</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-secondary">Voltar para a Lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

scryrall-admin/Views/Cartas/Delete.cshtml
@model scryrall_admin.Models.Carta

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carta</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FotoUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FotoUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

scryrall-admin/Views/Cartas/Details.cshtml
@model scryrall_admin.Models.Carta

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<div>
    <h4>Carta</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FotoUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FotoUrl)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayFor(model => model.Link)
        </dt>
        <dd>
            <table class="table">
                <tr>
                    <th>Foto</th>
                    <th>Logo icone</th>
                    <th>Coleção carta</th>
                    <th>Nome Ilustrador</th>
                    <th>Ano de lançamento</th>
                    <th>Url da Página</th>
                </tr>
                <tr>
                    <td>
                        <img src="@Model.FotoUrl" alt="image film" style="max-width: 200px; max-height: 300px;" />
                    </td>

                    <td>
                        @if (Model.Colecao != null)
                        {
                            <img src="@(!string.IsNullOrEmpty(Model.Colecao.LogoUrl) ? Url.Content(Model.Colecao.LogoUrl) : "https://logodix.com/logo/298915.png")" alt="image film" style="max-width: 200px; max-height: 300px;" />
                        }
                        else
                        {
                            <img src="https://logodix.com/logo/298915.png" alt="image film" style="max-width: 200px; max-height: 300px;" />
                        }
                    </td>


                
                    <td>
                        @Html.DisplayFor(model => model.Colecao.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Ilustrador.Nome)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Colecao.Ano)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Link.Url)
                    </td>
                </tr>
            </table>



        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

scryrall-admin/Views/Cartas/Edit.cshtml
@model scryrall_admin.Models.Carta

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Carta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FotoUrl" class="control-label"></label>
                <input asp-for="FotoUrl" class="form-control" />
                <span asp-validation-for="FotoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link.Url" class="control-label">Link URL</label>
                <input asp-for="Link.Url" class="form-control" />
                <span asp-validation-for="Link.Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ilustrador.Nome" class="control-label">Nome Ilustrador</label>
                <input asp-for="Ilustrador.Nome" class="form-control" />
                <span asp-validation-for="Ilustrador.Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colecao.Nome" class="control-label">Nome Coleção</label>
                <input asp-for="Colecao.Nome" class="form-control" />
                <span asp-validation-for="Colecao.Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colecao.Ano" class="control-label"></label>
                <input asp-for="Colecao.Ano" class="form-control" />
                <span asp-validation-for="Colecao.Ano" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Colecao.LogoUrl" class="control-label"></label>
                <input asp-for="Colecao.LogoUrl" class="form-control" />
                <span asp-validation-for="Colecao.LogoUrl" class="text-danger"></span>
            </div>




            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

scryrall-admin/Views/Cartas/Index.cshtml
@model IEnumerable<scryrall_admin.Models.Carta>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Cartas</h1>
<p>Aqui você pode encontrar uma lista de todas as cartas gerenciadas na plataforma.</p>
<p>
    <a asp-action="Create">Criar Nova Carta</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                <!-- Coluna da Imagem -->
                @Html.DisplayNameFor(model => model.FotoUrl)
            </th>
            <th>
                <!-- Coluna do Tipo -->
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th>
                <!-- Coluna da Descrição -->
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <!-- Imagem da Carta -->
                    @if (item.FotoUrl != null)
                    {
                        <img src="@Url.Content(item.FotoUrl)" alt="Imagem da Carta" style="max-width: 200px; max-height: 300px;" />
                    }
                </td>

                <td>
                    <!-- Tipo da Carta -->
                    @Html.DisplayFor(modelItem => item.Tipo)
                </td>
                <td>
                    <!-- Descrição da Carta -->
                    @Html.DisplayFor(modelItem => item.Descricao)
                </td>

                <td>
                    <!-- Links para Editar, Detalhes e Excluir -->
                    <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

scryrall-admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem-vindo à Plataforma de Gerenciamento de Cartas</h1>
    <p>A nossa plataforma oferece uma solução completa para gerenciar e controlar todas as suas cartas de forma eficiente.</p>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <h2>O que oferecemos</h2>
            <p>Nossa plataforma permite que você organize, pesquise e visualize todas as informações relacionadas às suas cartas. Com recursos avançados de pesquisa e categorização, você pode encontrar facilmente as cartas que precisa para seus projetos.</p>
        </div>
        <div class="col-md-6">
            <img src="https://th.bing.com/th/id/R.ff579882cc1984671cfbf937e5623be8?rik=FXiiEo5JPgs6uQ&riu=http%3a%2f%2fwallpapercave.com%2fwp%2f1HNuyzn.jpg&ehk=AB7IqRNrCEgM1ZeE%2fQX1H4D%2b8Zx9wjuyVT19dHN%2b2KI%3d&risl=&pid=ImgRaw&r=0" alt="Banner 1" class="img-fluid">
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img src="https://cdn.discordapp.com/icons/617081823658246260/1f62957f7fc01b4b4fa77269ca3e9afc.png?size=512" alt="Banner 2" class="img-fluid">
        </div>
        <div class="col-md-6">
            <h2>Recursos Avançados</h2>
            <p>Nossos recursos avançados incluem:</p>
            <ul>
                <li>Gestão de imagens das cartas.</li>
                <li>Detalhes completos sobre cada carta, incluindo nome, tipo e descrição.</li>
                <li>Informações sobre a coleção da carta e o ilustrador.</li>
                <li>Links para a página oficial de cada carta.</li>
            </ul>
        </div>
    </div>
</div>

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <h2>Como Começar</h2>
            <p>Comece a usar nossa plataforma agora mesmo:</p>
            <ol>
                <li>Faça o login na sua conta.</li>
                <li>Adicione suas cartas à biblioteca.</li>
                <li>Explore as funcionalidades avançadas para organizar suas cartas.</li>
                <li>Desfrute de um controle completo sobre suas cartas!</li>
            </ol>
        </div>
        <div class="col-md-6">
            <img src="https://th.bing.com/th/id/OIP.Z7CurXmaKg6g61_sp3Y_HwHaEo?pid=ImgDet&rs=1" alt="Banner 3" class="img-fluid">
        </div>
    </div>
</div>

scryrall-admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - scryrall_admin</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/scryrall_admin.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">scryrall_admin</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cartas" asp-action="Create">Criar Carta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cartas" >Exibir Cartas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - scryrall_admin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>